Repository GlaucoB0/gerenciamento-ypua, pull requests merged in 2024-11, with the labels that each got.

#6 Server-Side finished
  back-end/prisma/schema.prisma
  back-end/src/app.ts
  back-end/src/controllers/controllerClientes.ts
  back-end/src/controllers/controllerQuartos.ts
  back-end/src/controllers/controllerTarefas.ts
  back-end/src/helpers/zodValidations.ts
  back-end/src/interfaces/interfaces.ts
  back-end/src/routes/rotaClientes.ts
  back-end/src/routes/rotaFuncionarios.ts
  back-end/src/routes/rotaQuartos.ts
  back-end/src/routes/rotaTarefas.ts
  back-end/src/routes/router.ts
  back-end/src/services/clientesServices.ts
  back-end/src/services/quartosServices.ts
  back-end/src/services/tarefasServices.ts
Labels: enhancement

#5 Aprimorar roteamento
  frontend/src/App.jsx
  frontend/src/hooks/viewLoaders.js
  frontend/src/main.jsx
  frontend/src/views/LoginView/LoginView.jsx
Labels: enhancement

#9 Adicionando CORS e aprimorando tratamento de erros em POST /funcionarios/login
  back-end/package-lock.json
  back-end/package.json
  back-end/src/app.ts
  back-end/src/controllers/controllerFuncionarios.ts
Labels: bug, enhancement

#20 Feature: Redirecionamento + alinhamento das páginas em Dashboard
  frontend/src/App.jsx
  frontend/src/components/Card/Card.jsx
  frontend/src/components/Card/Card.module.sass
  frontend/src/main.jsx
  frontend/src/views/Dashboard/Dashboard.jsx
  frontend/src/views/Dashboard/Dashboard.module.sass
Labels: enhancement, help wanted

#25 Visão Geral (~50%) + Logout + Refatorações no Modal
  frontend/src/App.jsx
  frontend/src/components/Button/Button.jsx
  frontend/src/components/Button/Button.module.sass
  frontend/src/components/Form/FormControlRoot/FormControlRoot.jsx
  frontend/src/components/Form/FormSubmit/FormSubmit.module.sass
  frontend/src/components/HeadedCard/HeadedCard.jsx
  frontend/src/components/HeadedCard/HeadedCard.module.sass
  frontend/src/components/Modal/Modal.jsx
  frontend/src/components/Modal/Modal.module.sass
  frontend/src/components/Model/Model.jsx
  frontend/src/components/Text/Text.jsx
  frontend/src/components/Text/Text.module.sass
  frontend/src/hooks/loaders/listaDeHospedesLoader.js
  frontend/src/hooks/loaders/visaoGeralLoader.js
  frontend/src/hooks/tasks/deleteReserva.js
  frontend/src/pages/CriarAcomodacao/CriarAcomodacao.jsx
  frontend/src/pages/CriarFuncionario/CriarFuncionario.jsx
  frontend/src/pages/ListaDeHospedes/ListaDeHospedes.jsx
  frontend/src/pages/ListaDeHospedes/ListaDeHospedes.module.sass
  frontend/src/pages/VisaoGeral/VisaoGeral.jsx
  frontend/src/pages/VisaoGeral/VisaoGeral.module.scss
  frontend/src/styles/_elements.sass
  frontend/src/styles/_variables.scss
  frontend/src/views/Dashboard/Dashboard.jsx
  frontend/src/views/Dashboard/Dashboard.module.sass
Labels: enhancement
